/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.snake.code;

import java.awt.*;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author user85
 */
public class showSplashScreen extends javax.swing.JPanel {

    /**
     * Creates new form showSplashScreen
     */
    public showSplashScreen(Frame gameFrame) {
        initComponents();
        setLayout(new BorderLayout());
        setPreferredSize(new Dimension(700, 700));
        addImage();

        ScheduledExecutorService executor = Executors.newSingleThreadScheduledExecutor();
        executor.schedule(() -> {
            gameFrame.switchPanel(new mainMenu(gameFrame));
        }, 2, TimeUnit.SECONDS);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splashImagePanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(176, 226, 176));

        javax.swing.GroupLayout splashImagePanelLayout = new javax.swing.GroupLayout(splashImagePanel);
        splashImagePanel.setLayout(splashImagePanelLayout);
        splashImagePanelLayout.setHorizontalGroup(
            splashImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 333, Short.MAX_VALUE)
        );
        splashImagePanelLayout.setVerticalGroup(
            splashImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 255, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(splashImagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(splashImagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(258, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel splashImagePanel;
    // End of variables declaration//GEN-END:variables

    private void addImage() {
        Image snakeLogo = new ImageIcon("src/main/java/org/snake/Images/Snake Logo.jpeg").getImage();
        JLabel picLabel = new JLabel(new ImageIcon(snakeLogo));
        add(picLabel);
    }

}
